商旅管理: "xpath==//a[contains(text(), '商旅管理')]"
出差设置: "xpath==//sidebar/ul[1]/li[2]/div[1]"
事中授权设置: "xpath==//a[contains(text(), '事中授权设置')]"

# 授权规则配置
设置授权规则: "xpath==//span[contains(text(),'设置授权规则')]/.."
授权管控开关: "xpath==//nz-switch[@formcontrolname='authorizeEnabled']/button[1]"
订单均需授权: "xpath==//span[@class='ant-radio ant-radio-checked']"
改签需授权: "class==ant-checkbox-inner" # 第一个
退票需授权: "class==ant-checkbox-inner" # 第二个
国内机票: "class==ant-checkbox-inner" # 第三个
国内酒店: "class==ant-checkbox-inner" # 第四个
保存: "xpath==//span[contains(text(),'保存')]/.."
保存结果: "xpath==//div[contains(@class,'ant-message-custom-content')]/span[1]" # 修改保存是否提交成功
预订选择: "xpath==//label[contains(text(),'预订选择')]"  # 判断授权是否开始

# 授权人配置
二级授权人姓名: "xpath==//tbody/tr[3]/td[3]/span[2]" # 若有才有该元素
修改: "xpath==//tbody/tr[3]/td[5]/span[2]/a[1]"  # 基础授权流
二级授权人删除: "xpath==//th-employee-select[@formcontrolname='secondAuditEmployees']/nz-select[1]/nz-select-top-control[1]/nz-select-item[1]/span[1]/i[1]"
二级授权人输入框: "xpath==//th-employee-select[@formcontrolname='secondAuditEmployees']/nz-select[1]"
二级授权人输入: "xpath==//th-employee-select[@formcontrolname='secondAuditEmployees']/nz-select[1]/nz-select-top-control[1]/nz-select-search[1]/input[1]"
选中二级授权人: "xpath==//nz-option-item[contains(@title,'{0}')]"
保存: "xpath==//span[contains(text(),'保存')]/.."
修改结果: "xpath==//div[contains(@class,'ant-message-custom-content')]/span[1]"
