商旅管理: "xpath==//a[contains(text(), '商旅管理')]"
出差设置: "xpath==//sidebar/ul[1]/li[2]/div[1]"
事前审批设置: "xpath==//a[contains(text(), '事前审批设置')]"
二级审批人姓名: "xpath==//tbody/tr[3]/td[3]/span[2]" # 该元素有文字则说明有设置
修改: "xpath==//tbody/tr[3]/td[5]/span[2]/a[1]"  # 基础审批流--暂只设置基础审批流
二级审批人删除: "xpath==//th-employee-select[@formcontrolname='secondAuditEmployees']/nz-select[1]/nz-select-top-control[1]/nz-select-item[1]/span[1]/i[1]"
二级审批人输入框: "xpath==//th-employee-select[@formcontrolname='secondAuditEmployees']/nz-select[1]"
二级审批人输入: "xpath==//th-employee-select[@formcontrolname='secondAuditEmployees']/nz-select[1]/nz-select-top-control[1]/nz-select-search[1]/input[1]"
选中二级审批人: "xpath==//nz-option-item[contains(@title,'{0}')]"
保存: "xpath==//span[contains(text(), '保存')]/.."
修改结果: "xpath==//div[contains(@class,'ant-message-custom-content')]/span[1]"
